export const SLIDES = [
  "hero",
  "problem",
  "loss",
  "everyday-benefits",
  "voice-agent",
  "qualify-experience",
  "qualify",
  "confirm",
  "demo",
  "engine",
  "traction",
  "founder",
  "enterprise-grade",
  "why-wins",
  "path",
  "moats",
  "vision",
  "ask",
  "appendix",
  "capture-detail",
  "connect-detail",
  "convert-detail",
];

export const PDF_EXPORT_SLIDES = SLIDES.filter((slide) => slide !== "demo");
